"""update foreign keys

Revision ID: 361c3151a564
Revises: 4f52f6916c55
Create Date: 2024-08-16 18:06:27.548813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '361c3151a564'
down_revision = '4f52f6916c55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
