"""update foreign keys

Revision ID: 4f52f6916c55
Revises: 58a18d6cd3e5
Create Date: 2024-08-16 18:03:17.482141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f52f6916c55'
down_revision = '58a18d6cd3e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
