"""update column name

Revision ID: 58a18d6cd3e5
Revises: 846f3a9f66a3
Create Date: 2024-08-16 17:59:12.659231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58a18d6cd3e5'
down_revision = '846f3a9f66a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
