"""Create base models for User, Chatroom and ChatMessage

Revision ID: 846f3a9f66a3
Revises: 
Create Date: 2024-08-16 17:03:30.279332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '846f3a9f66a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('chat_room',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('chat_type', sa.Enum('SINGLE', 'GROUP', name='chat_type'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_room_id'), 'chat_room', ['id'], unique=False)
    op.create_index(op.f('ix_chat_room_name'), 'chat_room', ['name'], unique=False)
    op.create_table('user_chat_room',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('chat_room_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat_room_id'], ['chat_room.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_chat_room_chat_room_id'), 'user_chat_room', ['chat_room_id'], unique=False)
    op.create_index(op.f('ix_user_chat_room_id'), 'user_chat_room', ['id'], unique=False)
    op.create_index(op.f('ix_user_chat_room_user_id'), 'user_chat_room', ['user_id'], unique=False)
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('user_chat_room_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_chat_room_id'], ['user_chat_room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_message_id'), 'chat_message', ['id'], unique=False)
    op.create_index(op.f('ix_chat_message_text'), 'chat_message', ['text'], unique=False)
    op.create_index(op.f('ix_chat_message_user_chat_room_id'), 'chat_message', ['user_chat_room_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_message_user_chat_room_id'), table_name='chat_message')
    op.drop_index(op.f('ix_chat_message_text'), table_name='chat_message')
    op.drop_index(op.f('ix_chat_message_id'), table_name='chat_message')
    op.drop_table('chat_message')
    op.drop_index(op.f('ix_user_chat_room_user_id'), table_name='user_chat_room')
    op.drop_index(op.f('ix_user_chat_room_id'), table_name='user_chat_room')
    op.drop_index(op.f('ix_user_chat_room_chat_room_id'), table_name='user_chat_room')
    op.drop_table('user_chat_room')
    op.drop_index(op.f('ix_chat_room_name'), table_name='chat_room')
    op.drop_index(op.f('ix_chat_room_id'), table_name='chat_room')
    op.drop_table('chat_room')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
